[package]
name = "sdl3-sys"
version = "0.0.10-dev+sdl3-prerelease-3.1.2-1876-g53bf2baac"
edition = "2021"
authors = ["Maia S. R."]
license = "Zlib"
description = "Rust bindings for version 3 of the SDL library (Simple DirectMedia Layer)"
repository = "https://github.com/maia-s/sdl3-sys-rs"
documentation = "https://docs.rs/sdl3-sys"
keywords = ["sdl", "windowing", "graphics"]
categories = ["external-ffi-bindings", "rendering", "game-development", "multimedia", "no-std"]

[features]
default = []

# Implement the Debug trait for applicable types
debug-impls = []

# These are mutually exlusive; if more than one is enabled, the former in the list is used
# (so e.g. disabled overrides release). If none are selected, either release or debug will
# be enabled based on the build profile
assert-level-disabled = []
assert-level-release = []
assert-level-debug = []
assert-level-paranoid = []

# Used to enable core::ffi::VaList
nightly = []

[package.metadata.docs.rs]
all-features = true
