[package]
name = "sdl3-sys"
version = "0.0.9+sdl3-3.1.2"
edition = "2021"
authors = ["Maia S. R."]
license = "Zlib"

[features]
default = []

# These are mutually exlusive; if more than one is enabled, the former in the list is used
# (so e.g. disabled overrides release). If none are selected, either release or debug will
# be enabled based on the build profile
assert-level-disabled = []
assert-level-release = []
assert-level-debug = []
assert-level-paranoid = []

# Used to enable core::ffi::VaList
nightly = []
